concurrency: ci-${{ github.ref }}

name: Docker build

on:
  #pull_request:
  #push:
    #paths: [/**]
  workflow_dispatch:

jobs:
  build:
    if: github.ref_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: /

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Get timestamp
        run: |
          echo timestamp="$(date +%s)" >> $GITHUB_ENV
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login.outputs.registry }}/${{ github.ref_name }}
          tags: |
            type=sha,suffix=-${{ env.timestamp }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
